version: "3.7"

services:
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./loki-stack/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - loki

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  spider1:
    build: ./spiders
    container_name: spider1

  spider2:
    build: ./spiders
    container_name: spider2
